version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      
    commands:
      - npm install
      
  build:
    commands:
       - npm run build
       
  post_build:
    commands:
      - aws s3 cp --recursive ./dist s3://<s3 bucket id>/
      - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://<s3 bucket id>/
      - aws cloudfront create-invalidation --distribution-id <distribution id> --paths /index.html
      
artifacts:
    files:
      - "dist/*"
      - "dist/**/*"